### ISSUE TITLE
Can't use adb shell on STYTJ02YM (3.5.3_0047)

### ISSUE THREAD

**Issue by angellobodj** [rumpeltux/viomi-rooting#10]
I can successfully push the modified `adb_shell` code to `/bin/adb_shell` on a STYTJ02YM with 3.5.3_0047, however everytime I try to "`adb shell`" something I get error as if the file wouldn't exist:
`- exec '/bin/adb_shell' failed: No such file or directory (2) -`

**My `adb_shell` content:**
```
#!/bin/sh
export ENV='/etc/adb_profile'
exec /bin/sh "$@"
```

**In short:**
I can use push and pull commands, but when I try to "`adb shell`" it doesn't want to execute any shell so I can't passwd nor anything.

**Already tested:**
- After pushing my modified `adb_shell`, I can get it back through adb pull and in fact it is the same file I pushed before (in case there was something removing/overwriting my adb_shell after pushing it).
- Tried changing ownership of file and even setting permissions to 777, but it's still non executable by adb.
- Also checked that ssh root@x.x.x.x throws "Connection refused", it doesn't even ask for login.

Someone else had this problem or know how to workaround it?

Thanks in advance.

**Comment by rumpeltux** [comment]
Can you try with this contents instead?

```
#!/bin/sh
export ENV='/etc/adb_profile'
exec /bin/sh $@
```

(no quotes around `$@`)

**Comment by angellobodj** [comment]
> Can you try with this contents instead?
> 
> ```
> #!/bin/sh
> export ENV='/etc/adb_profile'
> exec /bin/sh $@
> ```
> 
> (no quotes around `$@`)

Same issue @rumpeltux:
```
$ adb shell
- exec '/bin/adb_shell' failed: No such file or directory (2) -
[adbd D](null): received remote packet, sending to transport
[adbd D]about to read (fd=8, len=24)
[adbd D]LS(704): closed
[adbd D]readx: fd=10 wanted=4
[adbd D]readx: fd=10 wanted=4 got=4
[adbd DR]0d000000 ....
[adbd D]transport_socket_events(fd=11, events=0001,...)
[adbd D]handle_packet() CLSE
[adbd D][ done fd=8 ]
[adbd D]about to read (fd=8, len=7)
[adbd D][ done fd=8 ]
[adbd D](null): received remote packet, sending to transport
[adbd D]about to read (fd=8, len=24)
[adbd D]transport_socket_events(fd=11, events=0001,...)
[adbd D]handle_packet() OPEN
```

**Comment by rumpeltux** [comment]
The raw adb shell may be broken but does `adb shell ls` work?
(reinstall the version with quotes around "$@")

**Comment by angellobodj** [comment]
> The raw adb shell may be broken but does `adb shell ls` work?
> (reinstall the version with quotes around "$@")

Somehow I managed to make it work without the quotes, however I restored the robot code thinking it was all done and then I noticed I didn't change root password and also ssh wasn't correctly set up (lol) so I am trying to repeat the process and surprisingly now I can't even delete the `/etc/rc.d/S90robotManager` file:
```
BusyBox v1.24.1 () multi-call binary.

Usage: rm [-irf] FILE...

Remove (unlink) FILEs

	-i	Always prompt before removing
	-f	Never prompt
	-R,-r	Recurse
```
It is like the `rm` command is not being called correctly, but I'd swear it is:
`while true; do (adb shell rm /etc/rc.d/S90robotManager && echo "Done") 2>&1 | grep -v "no devices/emulators found"; done`

Also tried with `rm -f` but same story. Like before I tried pulling the file to local and in fact it is still there, not being deleted (anyway I think I should get the '`no such file or directory`' warning rather than the '`usage`' text if it worked previously).

This thing looks like a really simple few commands process but it is actually giving some headache already :/

**Comment by rumpeltux** [comment]
Probably you do need the quotes around "$@" otherwise it drops the arguments or so and thus it only executes "rm" instead of "rm /etc/rc.d/S90robotManager"

**Comment by angellobodj** [comment]
Hi @rumpeltux and sorry for the big delay in my answer. I was out of home for a few days and I couldn't test anymore. Now I am back and glad to tell that I solved all the problems.

About the `- exec '/bin/adb_shell' failed: No such file or directory (2) -` error, I found out that the adb_shell is indeed being correctly pushed into the robot and the file is correct itself as well as the permissions, however it looks like the OS or adb is not properly detecting it, then I checked that restarting computer is enough to make it work.

So in my case the steps to make the whole process work was:

1. Copy adb_shell to robot (`adb push`).
2. Restart computer
3. Remove the robot autostart (`rm /etc/rc.d/S90robotManager`)
4. Restart computer
5. Complete the rest of the process (set up dropbear, ssh and/or install Valetudo)

Then the robot remains correctly rooted and accessible through ssh keys (shouldn't use password since it will eventually get automatically reset and you may lose access and need to repeat the whole process again).

I thought I would report back my experience in case someone faces the same issue.

PS: I was using a **live USB** with latest **Ubuntu** version, and I don't know if perhaps that might be the reason for these weird problems and having to restart computer after each step.

I hope my info can help in some way.

Thank you very much for the hints given before.

Best regards!

**Comment by rumpeltux** [comment]
Glad to hear that this got resolved for you! :-)

**Comment by ooii** [comment]
May I ask why restarting the computer twice helps?

**Comment by angellobodj** [comment]
> May I ask why restarting the computer twice helps?

Honestly I don't know. In my case I suspect it could be because I used Ubuntu from a live USB or something like that.

Maybe if you got Linux installed on your disk you don't need my workaround, but for me it was mandatory to restart the computer, Otherwise, without restarting computer I only managed to make the whole process work just once and never again in like 200+ attempts.

Best regards.

**Comment by Natogs** [comment]
Hello everyone.
I know this is an old issue, but I'm facing the same - exec '/bin/adb_shell' failed: No such file or directory (2) - problem with a Conga 3290 robot. 
adb_shell file has been pushed successfully.
I'm using Ubuntu 22.04.4 LTS through WSL in Windows. Rebooting the Linux subsystem did not solve it for me.
adb commands such as pull, push, reboot are working fine, but the adb shell throws me this error
Any idea how I could get it to work?
Thanks in advance
