### ISSUE TITLE
script overwrites existing .ssh/config without  any warning

### ISSUE THREAD

**Issue by asienski** [rumpeltux/viomi-rooting#14]
I suggest using something like:

test -w "$HOME/.ssh/config" || (echo "Cannot edit ~/.ssh/config."; exit)

instead of:
echo -n > "$HOME/.ssh/config" || (echo "Cannot edit ~/.ssh/config."; exit)

**Comment by rumpeltux** [comment]
Ouch. Thanks for reporting this!
