### ISSUE TITLE
Error: Device (Null) not found

### ISSUE THREAD

**Issue by Subtixx** [rumpeltux/viomi-rooting#17]
Using ubuntu the script spams the console with that, and refuses to work because of it

![grafik](https://user-images.githubusercontent.com/20743379/103423168-746e3a00-4ba5-11eb-88db-039b5f08ef4e.png)

Model: STYTJ02YM

**Comment by rumpeltux** [comment]
Might be a different ADB version…

Try to adjust the filters ("no devices/emulators found") in https://github.com/rumpeltux/viomi-rooting/blob/master/viomi-root.sh#L70 (and below)

**Comment by Subtixx** [comment]
Unfortunately that didn't work either. It doesn't print out anything anymore but after about 30 tries it still hasn't patched the ssh

**Comment by rumpeltux** [comment]
Sorry, I have no idea how to help you further, except for maybe try using a different computer. If you learn anything let us know.

**Comment by Subtixx** [comment]
I think the issue is with the piping.

Changing piping to 2< or something. Like redirecting all output to grep seemed to work. Although it said: "can't rm error: device not found" BUT it did replace adb_shell and I was able to go on manually after that.
