### ISSUE TITLE
Re-enable Mi Home Cloud Service

### ISSUE THREAD

**Issue by panoslouk** [rumpeltux/viomi-rooting#18]
Hello

I'm trying to re-enable the Mi Home Cloud Service, Anyway to do that?

**Comment by alexlex1997** [comment]
iptables -F

**Comment by panoslouk** [comment]
Thanks!!!

**Comment by fm94** [comment]
iptables will be re-initiated after every restart, a better option would be to remove the rules in `/etc/rc.d/S51valetudo` specifically the last for loop.
