### ISSUE TITLE
Not able to pull .ipk file.

### ISSUE THREAD

**Issue by johnappletree** [rumpeltux/viomi-rooting#19]
I want to say thank you for your useful bash script!
unfortunately I got following error.

```
wget https://itooktheredpill.irgendwo.org/static/2020/dropbear_2015.71-2_sunxi.ipk
--2021-01-07 19:57:50--  https://itooktheredpill.irgendwo.org/static/2020/dropbear_2015.71-2_sunxi.ipk
Resolving itooktheredpill.irgendwo.org (itooktheredpill.irgendwo.org)... 37.187.99.185, 2001:41d0:a:23b9::1
Connecting to itooktheredpill.irgendwo.org (itooktheredpill.irgendwo.org)|37.187.99.185|:443... connected.
ERROR: cannot verify itooktheredpill.irgendwo.org's certificate, issued by ‘CN=R3,O=Let's Encrypt,C=US’:
  Unable to locally verify the issuer's authority.
To connect to itooktheredpill.irgendwo.org insecurely, use `--no-check-certificate'.

```
I hope 37.187.99.185 is your IP address? Otherwise, I might have fetched a wrong file as I proceeded using the --no-check-certificate option.

**Comment by rumpeltux** [comment]
This should be fixed. Looks like letsencrypt changed their intermediate CA and the old one was still configured on the webserver. I didn’t notice since the cert was perfectly valid in web browsers.

Thanks for letting me know!
