### ISSUE TITLE
Question about upgrade to 2021.1

### ISSUE THREAD

**Issue by Drun555** [rumpeltux/viomi-rooting#21]
Hey! Yesterday 2021.1 version was released.

I tried to manually copy binary file to /mnt/UDISK, added env variable to init.d daemon and changed IP adresses, but had no luck with it - webinterface just stays unreachable. Maybe you have a little remark in terms what should I do to manually upgrade? I'll be very appreciated, thanks in advance

**Comment by nygellyndley** [comment]
> 
> 
> Hey! Yesterday 2021.1 version was released.
> 
> I tried to manually copy binary file to /mnt/UDISK, added env variable to init.d daemon and changed IP adresses, but had no luck with it - webinterface just stays unreachable. Maybe you have a little remark in terms what should I do to manually upgrade? I'll be very appreciated, thanks in advance

Did you update `/etc/hosts` as well as `/etc/rc.d/S51valetudo`?

**Comment by Drun555** [comment]
Yes, I changed all entries to 203.0.113.1

Now i'll try to install netcat from opkg to see some logs. I'll post it here when it will be done

**Comment by Drun555** [comment]
Unfortunately there's nothing interesting. I'll attach logs below. Btw, there was no "miio_conf_check.temp" file in /mnt/UDISK/log


[log.txt](https://github.com/rumpeltux/viomi-rooting/files/5902848/log.txt)

**Comment by rumpeltux** [comment]
It’s probably broken because the viomi miio_client connects to a different IP.

You’ll need to compile yourself until there’s a newer release that includes https://github.com/Hypfer/Valetudo/pull/667
and follow the updated robot-setup instructions: https://valetudo.cloud/pages/installation/viomi.html#robot-setup
