### ISSUE TITLE
Can't get adb access

### ISSUE THREAD

**Issue by changetotower** [rumpeltux/viomi-rooting#22]
Hello. First of all, many thanks for this tool!

Unfortunately I can't get access via adb. Followed your steps exactly, adb is working generally and I've used a working cable. After the robot is turning on (voice saying "turning on"), I wait 2s, unplug und replug the cable on the computer (which is running latest Ubuntu) - nothing happens. Also not after many attempts. 

Any idea?

Thanks.

Model: Viomi V2 Pro / V-RVCLM21B (with latest FW)

**Comment by changetotower** [comment]
Well, actually still no luck. Tried with Raspberry Pi as well..

**Comment by rumpeltux** [comment]
Sorry to hear that. If you figure something out, let us know so that we can share the knowledge with others.
