### ISSUE TITLE
Viomi v8 - FW 3.5.8_0017

### ISSUE THREAD

**Issue by howdoyouturnthison0815** [rumpeltux/viomi-rooting#26]
Hi,
anyone sucessfully rooted the viomi v8 with FW 3.5.8_0017?
if i connect the usb the robot just says turning on but no adb connection can be established.
Tried it with a PC with Debian 10, Notebook with Ubuntu 20 and a Raspberry with newest os. Also a few different cables.
ADB shell with android phone is working.

dmesg shows the device and shortly after a disconnect.
[ 4253.744425] usb 1-1.1.2: new high-speed USB device number 62 using dwc_otg
[ 4253.874705] usb 1-1.1.2: New USB device found, idVendor=1f3a, idProduct=efe8, bcdDevice=ff.ff
[ 4253.874733] usb 1-1.1.2: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[ 4256.781810] usb 1-1.1.2: USB disconnect, device number 62

so it looks like it does not show as Android?

if anybody got some pointers i would be thankfull.

**Comment by spn91** [comment]
I have the exact same Firmware Version and the same problem. It seems that our device is not compatible :(

**Comment by howdoyouturnthison0815** [comment]
yeah figured that something changed. sent it back and will try it with an s6 Pure since that should work with dustcloud/valetudo

**Comment by Dropaq** [comment]
@howdoyouturnthison0815 here you go https://github.com/rumpeltux/python-miio/issues/1#issuecomment-915647117
