### ISSUE TITLE
Rooting Xiaomi Viomi V2 PRO "error: device offline" and "error: no devices/emulators found"

### ISSUE THREAD

**Issue by IT-freak-Jake** [rumpeltux/viomi-rooting#27]
Hi, I'm trying to root my Viomi V2 PRO but I'm getting this output after replugging the cable several times. I'm trying to do this on Ubuntu 18 booted from pendrive LIVE

root@ubuntu:/home/ubuntu/Desktop# ./viomi-root.sh
/tmp/viomi-root /home/ubuntu/Desktop
Starting viomi rooting procedure. Please make sure of the following before starting:
1. Your robot connects to your wifi when booted and your computer is connected to the same network.
2. It is powered off
3. You have a working micro-USB cable plugged into the robot and ready to plug into your computer.

Press [Enter] to continue

Checking if SSH is already configured and working
SSH not configured
We'll now try to connect to the ADB shell. Please connect the USB cable to your computer.
If you hear the Robot voice ('kaichi'), wait another two seconds and unplug and reconnect the cable.
If nothing happens try replugging the USB cable. This may take 10 or more attempts.
adb: error: failed to get feature set: device offline
Shell fixed...
error: device offline
error: device offline
error: device offline
error: device offline
error: device offline
error: device offline
error: device offline
error: device offline
error: device offline
error: device offline
error: device offline
error: device offline
error: device offline
error: device offline
error: device offline
error: device offline
error: device offline
error: device offline
error: device offline
error: device offline
error: device offline
error: device offline
error: device offline
error: device offline
error: device offline
error: device offline
error: device offline
error: device offline
error: device offline
error: device offline
error: device offline
error: device offline
error: device offline
error: device offline
error: device offline
error: device offline
error: device offline
error: device offline
error: device offline
error: device offline
error: device offline
error: device offline
error: device offline
error: device offline
error: device offline
error: device offline
error: device offline
error: device offline
error: device offline
error: device offline
error: device offline
error: device offline
error: device offline
error: device offline
error: device offline
error: device offline
error: device offline
error: device offline
error: device offline
error: device offline
error: device offline
error: device offline
error: device offline
error: device offline
error: device offline
error: device offline
error: device offline
error: device offline
error: device offline
error: device offline
error: device offline
error: device offline
error: device offline
error: device offline
error: device offline
error: device offline
error: device offline
error: device offline
error: device offline
error: device offline
error: device offline
error: no devices/emulators found
error: no devices/emulators found
error: no devices/emulators found
error: no devices/emulators found
error: no devices/emulators found
error: no devices/emulators found
error: no devices/emulators found
error: no devices/emulators found
error: no devices/emulators found
error: no devices/emulators found
error: no devices/emulators found
error: no devices/emulators found
error: no devices/emulators found
error: no devices/emulators found
error: no devices/emulators found
error: no devices/emulators found
error: no devices/emulators found
error: no devices/emulators found
error: no devices/emulators found
error: no devices/emulators found
error: no devices/emulators found
error: no devices/emulators found
error: no devices/emulators found
error: no devices/emulators found
error: no devices/emulators found
error: no devices/emulators found
error: no devices/emulators found

**Comment by rumpeltux** [comment]
This tool is only for v7/v8. Should you discover that other robots also work similarly, I’m happy to review a pull request.
