### ISSUE TITLE
Can't connect to device via adb for FW 3.5.8_0017

### ISSUE THREAD

**Issue by tincturaginseng** [rumpeltux/viomi-rooting#35]
Still not connect to device from #31 

OS: Arch Linux x86_64
Device: Viomi Vacuum Cleaner Mop P (STYTJ02YM)
Firmware: **3.5.8_0017**

My steps:

1. Turn off device
2. Disconnect battery
3. Connect micro-USB cable to robot
4. Hold down **Home key** and connect USB cable to PC
5. Press **Power key** for 10 times and release both - **Home** and **Power** keys
6. In _lsusb_ output I see _Allwinner Technology sunxi SoC OTG connector in FEL/flashing mode_ device for 3 seconds and it disconnect. Output for adb devices still empty
7. After that I hear "turning on" message and robot try to normal boot

[Video](https://user-images.githubusercontent.com/3119849/132990528-172776da-22b4-4a8d-b58a-11b9d70eeb57.mp4)

**Comment by rumpeltux** [comment]
So the tool doesn’t work? What’s its failure output? Looks like your entering flash mode rather than the adb shell?
Sorry, probably can’t be of help for this issue.
