### ISSUE TITLE
ERROR dropbear_2015.71-2_sunxi.ipk

### ISSUE THREAD

**Issue by razserv2010** [rumpeltux/viomi-rooting#38]
--2021-10-15 20:26:55--  https://itooktheredpill.irgendwo.org/static/2020/dropbear_2015.71-2_sunxi.ipk
Resolving itooktheredpill.irgendwo.org (itooktheredpill.irgendwo.org)... 37.187.99.185, 2001:41d0:a:23b9::1
Connecting to itooktheredpill.irgendwo.org (itooktheredpill.irgendwo.org)|37.187.99.185|:443... connected.
ERROR: The certificate of ‘itooktheredpill.irgendwo.org’ is not trusted.
ERROR: The certificate of ‘itooktheredpill.irgendwo.org’ has expired.
dropbear_2015.71-2_sunxi.ipk: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match

**Comment by rumpeltux** [comment]
I cannot reproduce this / may have been a transient issue.
