### ISSUE TITLE
scp not working

### ISSUE THREAD

**Issue by oangelo** [rumpeltux/viomi-rooting#47]
I could sucessfuly root my device, but I can't install valetudo.
i tried this:

> $scp valetudo-armv7 vacuum:.
>   ash: /usr/libexec/sftp-server: not found   
>   scp: Connection closed

and

> root@TinaLinux:/mnt/UDISK# wget https://github.com/Hypfer/Valetudo/releases/download/2022.06.0/valetudo-armv7
> wget: SSL support not available, please install ustream-ssl

also

> root@TinaLinux:/mnt/UDISK# opkg install ustream-ssl
> Unknown package 'ustream-ssl'.
> Collected errors:
> * opkg_install_cmd: Cannot install package ustream-ssl.
> root@TinaLinux:/mnt/UDISK# opkg update
> Downloading /base/Packages.gz.
> Failed to allocate uclient context
> Downloading /kernel/Packages.gz.
> Failed to allocate uclient context
> Downloading /packages/Packages.gz.
> Failed to allocate uclient context
> Collected errors:
> * opkg_download: Failed to download /base/Packages.gz, wget returned 1.
> * opkg_download: Failed to download /kernel/Packages.gz, wget returned 1.
> * opkg_download: Failed to download /packages/Packages.gz, wget returned 1.

**Comment by oangelo** [comment]
Since the problem is with https, I used 
`python3 -m http.server`
to set a simple http server to be able to copy the valetudo file to the robot, using:
> wget http://<IP>:8000/valetudo-armv7

**Comment by DanielsSt** [comment]
I managed to get around this by using `scp` with `-O` (uppercase o) flag.
According the `man` page it uses legacy protocol instead of sftp

In this case it would be:
```
scp -O valetudo-armv7 vacuum:.
```
