### ISSUE TITLE
Convert viomi v-8 (EU) to viomi v-7(CN)

### ISSUE THREAD

**Issue by xxTudorxx** [rumpeltux/viomi-rooting#5]
So I have a Xiaomi Vacuum Mop P(Pro) from Europe, and It does not get the latest firmware updates like the viomi v-7 from China, also I cannot use it with the chinese mainland region in xiaomi home. Is there a way to convert it to the viomi v-7 variant and use it as if it was bought from the chinese mainland?
Also Xiaomi Mi Vacuum Mop P(EU) = STYTJ02YM = viomi v-8
And Xiaomi mi vacuum Mop P(CN) = STYJ02YM = viomi v-7
I have a idea to cancel the noise made by the vacuum by recording the noise, inverting it and replacing the sound that plays when the vacuum is started with the inverted track of the noise
Also I am very bad with the adb shell or whatever shell is used to controll the vacuum, if someone with experience and knowledge could tell me what commands to use and in wich order it will be very helpful.
Thanks in advance!
Also, english is my second language, so sorry for any typing mystake.
If I succed at canceling the noise made by the vacuum i will put here a video of it.

**Comment by rumpeltux** [comment]
This is out of scope of this tool. But feel free to try flashing a viomi-v7 image to your v8. Sending flash commands only works on the cloud interface, there’s currently no tooling to interact with that though (aside from http://valetudo.cloud/). I won’t be able to provide any assistance with that process and please be aware this could easily brick your robot.

**Comment by xxTudorxx** [comment]
Is there a way to take a backup of the vacuum before flashing and how can I restore the backup if something goes wrong?

**Comment by rumpeltux** [comment]
> Is there a way to take a backup of the vacuum before flashing

Yes, you can backup the /dev/nand* partitions (be sure to also note the major and minor numbers in `ls -al /dev/nand*`) and restore them if you still have root access to the robot.

> how can I restore the backup if something goes wrong?

If you brick your robot or lose root access, you won’t be able to restore the partitions.

**Comment by KeiShadow** [comment]
Did you flash v7 firmware to v8 ?

**Comment by jbreitung** [comment]
Has anybody some news about getting the newer firmware 3.5.3_0047 to the EU version (STYTJ02YM)? I am still searching for any solution to get those many new functions to my device...
