### ISSUE TITLE
Can't install spotify via ssh after root

### ISSUE THREAD

**Issue by razserv2010** [rumpeltux/viomi-rooting#50]
I managed to root the device STYTJ02YM V8 now I'm trying to install spotify through this guide:
https://eddiez.me/spotify-vacuum/
But when I run this command:
apt-get install -y curl
I get
```
root@TinaLinux:~# apt-get install -y curl
-ash: apt-get: not found
```
and date:
```
root@TinaLinux:~# date
date: invalid date ''
date: invalid date ''
date: invalid date ''
```

**Comment by rumpeltux** [comment]
This is a different operating system. `apt-get` is not supported, so your guide is not applicable.

Out of curiosity: how did you root the device? Did you use this repository for it?
How do you know if you have v8 vs v7?

**Comment by razserv2010** [comment]
> This is a different operating system. `apt-get` is not supported, so your guide is not applicable.
> 
> Out of curiosity: how did you root the device? Did you use this repository for it? How do you know if you have v8 vs v7?

i did the root from this guide:
https://github.com/rumpeltux/python-miio/issues/1#issuecomment-915647117

from MiHome vevs app:

![image](https://user-images.githubusercontent.com/47921926/207723891-5c52d1d6-c552-4fb0-a7f9-a34d722be110.png)
