### ISSUE TITLE
Using the script without wifi

### ISSUE THREAD

**Issue by emmexx** [rumpeltux/viomi-rooting#57]
Not an issue but a question.

I never connected my xiaomi robot (viomi-v8) to a wifi network so I'm not sure what to do to use the script. Can I run it even if it never called home.
I'd like not to have to register it now and I seem to remember reading in some discussion that it is possible to enter the wifi data in /etc/wpa_supplicant
But I can't find that discussion and I don't want to brick the robot  (Meanwhile I found out, it's in the main github page.)

Is there a way to root the vacuum and install Valetudo without using the wifi or without registering with Xiaomi?

**Comment by rumpeltux** [comment]
I think that should be doable, but I’m not entirely sure.
