### ISSUE TITLE
A potential bug in the script that could potentially soft-brick your device, especially for newcomers.

### ISSUE THREAD

**Issue by kodbuzz** [rumpeltux/viomi-rooting#58]
Line 8:      `ssh-keygen -f "$HOME/.ssh/id_rsa.pub" || exit;`

Line 153:  `adb push ~/.ssh/id_rsa.pub /etc/dropbear/authorized_keys`

On Line 8, a keypair is generated with the private key named "id_rsa.pub" and the public key named "id_rsa.pub.pub." However, on Line 153, the script pushes the PRIVATE KEY to the target vacuum robot as authorized_keys, which should be the public key in this case under the filename "id_rsa.pub.pub". This mismatch causes a PERMISSION DENIED error in all SSH commands that follow, it removes the /etc/rc.d/S90robotManager in ADB shell but restore it by SSH, will is impossible in this case.

Failure to restore /etc/rc.d/S90robotManager in an ADB shell can lead the robot into a soft-brick state.

FIX:
Replace Line 8 `ssh-keygen -f "$HOME/.ssh/id_rsa.pub" || exit;` with:
`ssh-keygen -f "$HOME/.ssh/id_rsa" || exit;`

PS:
Anyone who is looking for a fixed script, please simply go to my fork:
https://github.com/kodbuzz/viomi-rooting

**Comment by rumpeltux** [comment]
Thanks, this was fixed in #52 already.
