### ISSUE TITLE
Unable to root STYTJ02YM under 3.5.3_0045

### ISSUE THREAD

**Issue by ooii** [rumpeltux/viomi-rooting#7]
Hi,
I'm trying to root my STYTJ02YM (Xiaomi Vacuum 8) and I'm not able to do so. I see that its support is experimental but does that mean that it may not work at all? I have one running 3.5.3_0045 (offering to update to 47).
I tried more than 50 times to unplug 2 seconds after the "kaichi" sound with no success. Each time, it restarts the device and I have the "kaichi" sound.
The script stops at 
```
* daemon not running; starting now at tcp:5037
* daemon started successfully
```
Note that I remove the battery when proceeding.

Thanks for your help.

**Comment by lchimaru** [comment]
I had the same problem, but on version 3.5.3_0047. Using different cable to connect device fixed it.

**Comment by ooii** [comment]
Thanks @lchimaru 
Just tested with 4 more cables, no luck. Is there any way to test a cable before using it? If a cable is able to provide power and works with some other data device (like hard drive), does it mean that it should be okay?

**Comment by lchimaru** [comment]
I used original usb cable from my previous phone. My guess was to use cable which I used before to transfer data. To be honest I was surprised it helped.

**Comment by rumpeltux** [comment]
You can try to connect an android phone (enable usb debugging on it) to verify that the cable works and adb can correctly connect to it, e.g. by using `adb shell`.

**Comment by ooii** [comment]
No luck, can't make it working :'(

**Comment by paradx** [comment]
I had a similar problem, I changed from my laptop ( Freebsd 12.1; X220 thinkpad) to  a raspberry pi, there it then worked flawlessly. 
Maybe it's something timing related with the USB controller and how fast the device/adb is exposed? 

I'm a bit curious about your version and and v8. I have a v8 STYTJ02YM and it has 3.5.3_0017 as current version (int version is not as frequently updated as the v7 chinese on it seems) but you seem to have the v7 FW running on v8? or is it just a production date version thing when they changed it from v7 to v8? 
Maybe it has to do something with that?

**Comment by ooii** [comment]
Thanks for the feedback. I'll try with another computer (I'm doing it on a USB3 port on a Nuc).
The model written on the bottom is STYTJ02YM and therefore, I thought it's a v8. So can it be a v7?

**Comment by rumpeltux** [comment]
Closing this for now. If you can’t get adb to work, this is outside the scope of this repo.

**Comment by paradx** [comment]
@ooii I do not know, but I read that the _0045 firmware is on the viomi.v7 aka mainland china version and the international/ CE certified vacuum has the v8 with fw version _0017 beeing the latest as of now.

**Comment by adjivas** [comment]
> You can try to connect an android phone (enable usb debugging on it) to verify that the cable works and adb can correctly connect to it, e.g. by using adb shell.

I have reproduced the test on a cable checked with the adb shell on two of my computers.
Unfortunately, I haven't success to root my viomi.v7 (STYJ02YM).

```
See [http://developer.android.com/tools/device.html] for more information
adb: insufficient permissions for device
See [http://developer.android.com/tools/device.html] for more information
adb: insufficient permissions for device
See [http://developer.android.com/tools/device.html] for more information
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
```

**Comment by rumpeltux** [comment]
Have you followed the link provided in the error message? in particular are you member of the plugdev group and have setup correct udev rules (`dmesg` would probably show you the device ids).

**Comment by adjivas** [comment]
Oups, thank's you @rumpeltux! Your question has helped me to show what I should really do.
In my case, I have created and added myself to the plugdev group.

**Comment by holkono** [comment]
@adjivas would you kindly explain what changes you made to the udev rules?
