### ISSUE TITLE
Problem during rooting

### ISSUE THREAD

**Issue by Nradar** [rumpeltux/viomi-rooting#9]
Hi,
I am trying to root the STYJ02YM, and I choose to install valetudo, after that the terminals shows something in the attached image
<img width="570" alt="root" src="https://user-images.githubusercontent.com/17895606/93101842-c5026b80-f678-11ea-870b-851ce03d3334.png">

The current situation is I followed the manual installation instruction on valetudo github, and i can ssh into the vacuum, but the webgui always shows loading state, and I try to reset to factory the vacuum it keeps showing the slow blinking white led, is the vacuum brick? Please help me! Thank you so much!

**Comment by rumpeltux** [comment]
SSH couldn’t be setup because you didn’t have an ssh key.
Please try again with the latest version, which does create one for you if you don’t have one.
